#!/usr/bin/env php
<?php

/*
|--------------------------------------------------------------------------
| Artisan Console Application
|--------------------------------------------------------------------------
|
| This file is the entry point for making various commands that you can call
| from your terminal, including the tinker command.
|
*/

if (file_exists(__DIR__.'/vendor/autoload.php')) {
    require __DIR__.'/vendor/autoload.php';
} else {
    require __DIR__.'/../../vendor/autoload.php';
}

$app = require_once __DIR__.'/bootstrap/app.php';

$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);

exit($kernel->handle(new Symfony\Component\Console\Input\ArgvInput, new Symfony\Component\Console\Output\ConsoleOutput));
